FROM php:apache
RUN apt-get update && apt-get install -y \
    libpng-dev libonig-dev libxml2-dev zip unzip git curl vim \
    default-mysql-client libpq-dev memcached redis-tools mailutils \
 && pecl install xdebug redis \
 && docker-php-ext-enable xdebug redis \
 && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd \
 && curl -sS https://getcomposer.org/installer | php \
 && mv composer.phar /usr/local/bin/composer \
 && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
 && apt-get install -y nodejs \
 && rm -rf /var/lib/apt/lists/*
WORKDIR /var/www/html
COPY docker/apache/000-default.conf /etc/apache2/sites-available/000-default.conf
RUN a2ensite 000-default.conf
EXPOSE 80
